apiVersion: cloudcredential.openshift.io/v1beta1
kind: CredentialsRequest
metadata:
  name: stuck-ebs-vols-aws-credentials
  namespace: openshift-monitoring
spec:
  secretRef:
    name: stuck-ebs-vols-aws-credentials
    namespace: openshift-monitoring
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1beta1
    kind: AWSProviderSpec
    statementEntries:
    - effect: Allow
      action:
      - ec2:DescribeInstances
      resource: "*"
