apiVersion: v1
kind: Service
metadata:
  labels:
    name: stuck-ebs-vols
  name: stuck-ebs-vols
  namespace: openshift-monitoring
spec:
  ports:
  - name: http-main
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    name: stuck-ebs-vols
  sessionAffinity: None
  type: ClusterIP
